### ISSUE TITLE
ConcurrentModificationException for concurrent users

### ISSUE THREAD

**Issue by milindaperera** [wso2-attic/carbon-gateway-framework#57]
Following error occurs when load test for passthrough sample with concurrent client threads

> [2016-10-21 12:18:19,642] ERROR {org.wso2.carbon.gateway.core.flow.Worker} - Error while mediating java.util.ConcurrentModificationException
>   at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
>   at java.util.LinkedList$ListItr.next(LinkedList.java:888)
>   at java.util.Collection.removeIf(Collection.java:414)
>   at org.wso2.carbon.messaging.Headers.set(Headers.java:56)
>   at org.wso2.carbon.gateway.outbounds.http.HTTPOutboundEndpoint.processRequest(HTTPOutboundEndpoint.java:64)
>   at org.wso2.carbon.gateway.outbounds.http.HTTPOutboundEndpoint.receive(HTTPOutboundEndpoint.java:42)
>   at org.wso2.carbon.gateway.core.flow.mediators.builtin.invokers.CallMediator.receive(CallMediator.java:109)
>   at org.wso2.carbon.gateway.core.flow.AbstractMediator.next(AbstractMediator.java:66)
>   at org.wso2.carbon.gateway.core.flow.mediators.builtin.manipulators.PropertyMediator.receive(PropertyMediator.java:83)
>   at org.wso2.carbon.gateway.core.flow.AbstractMediator.next(AbstractMediator.java:66)
>   at org.wso2.carbon.gateway.core.flow.mediators.builtin.manipulators.PropertyMediator.receive(PropertyMediator.java:83)
>   at org.wso2.carbon.gateway.core.flow.Worker.lambda$submit$2(Worker.java:70)
>   at org.wso2.carbon.gateway.core.flow.Worker$$Lambda$120/1839440963.run(Unknown Source)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)

**Comment by maheshika** [comment]
Closed, since the repo is deprecated.
